easy_admin:
  site_name: "<b>Back Office - Administrateur</b>"
  design:
    brand_color: 'blue'
    menu: 
      - label: 'E-commerce'
        icon: 'newspaper-o'
        children:
          - {entity: 'Product', icon: 'folder-open', label: 'Produits'}
          - {entity: 'Category', icon: 'folder-open', label: 'Categories'}
      - label: 'Administration'
        icon: 'user'
        children:
          - {entity: 'User', icon: 'folder-open', label: 'Utilisateurs'}

imports:
  - {resource: admin/}