easy_admin:
 entities:
    Product: 
      class: App\Entity\Product
      label: 'Produits'
      form:
        fields:
        - {property: 'name', label: 'Nom'}
        - {property: 'description', label: 'Description'}
        - {property: 'price', label: 'Prix'}
        - {property: 'imageFile', type: "file", label: "Ajouter une image"}
        - {property: 'category_id', label: "Catégorie"}
        - {property: 'user_id', label: "Posté par :"}
        - {property: 'updated_at',label: "Ajouté le :"}

      list:
        actions:
          - { name: "edit", icon: "pencil", label: false, css_class: "btn btn-primary" }
          - { name: "delete", icon: "trash", label: false, css_class: "btn btn-danger" }
        
        fields:
          - {property: 'name', label: 'Nom'}
          - {property: 'description', label: 'Description'}
          - {property: 'price', label: 'Prix'}
          - {property: 'image', type: "image", base_path: "images/products/", label: "Image"}
          - {property: 'category_id', label: 'Catégorie'}
          - {property: 'user_id', label: "Posté par :"}
          - {property: 'updated_at', type: "datetime",label: "Ajouté le :", format: "d/m/Y à H:i:s"}

    